version: 0.2

phases:
  pre_build:
    commands:
      - echo Creating Namespace...
      - docker ps | grep kube-apiserver
      - mkdir -p $HOME/.kube
      - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
      - sudo chown $(id -u):$(id -g) $HOME/.kube/config
      
  build:
    commands:
      - echo Build started on `date`
      - kubectl create namespace eks-sample-app
      - kubectl apply -f eks-sample-depl-nginx.yaml
      - kubectl apply -f eks-sample-service-ngnx.yaml
  post_build:
    commands:
      - echo Build completed on `date`
