version: 0.2

phases:
  pre_build:
    commands:
      - echo Creating Namespace...
      - kubectl create namespace eks-sample-app
  build:
    commands:
      - echo Build started on `date`
      - kubectl apply -f eks-sample-depl-nginx.yaml
      - kubectl apply -f eks-sample-service-ngnx.yaml
  post_build:
    commands:
      - echo Build completed on `date`
