apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service2
  namespace: eks-sample-app2
  labels:
    app: eks-sample-linux-app2
spec:
  selector:
    app: eks-sample-linux-app2
  ports:
    - protocol: TCP
      port: 4503
      targetPort: 4503
